"""Turns a Composition into C source.

Every layer is emitted as its own function taking the same input, and each is
instantiated against the composition's password, so all layers accept exactly the
same answer. `check()` calls them in a shuffled order so the sequence cannot be
assumed either.

The Python here and the emitted C have to agree exactly; `tests/test_generator.py`
proves it by compiling every composition and running the binary.
"""

from __future__ import annotations

import binascii
import random
import struct
from dataclasses import dataclass, field
from typing import Any

from .composer import Composition
from .techniques import FORMATS, POOL

TEA_DELTA = 0x9E3779B9
TEA_MARKER = b"AUTOCRACKME_OK!!"  # exactly 16 bytes: two XTEA blocks


@dataclass
class Generated:
    source: str
    password: str
    composition: Composition
    internals: list[dict[str, Any]] = field(default_factory=list)


@dataclass
class GenContext:
    """Composition plus the parameters decided before any layer is emitted."""

    composition: Composition
    params: dict[str, Any] = field(default_factory=dict)


@dataclass
class Layer:
    """One emitted check function: optional helpers, the function, and its specifics."""

    helpers: str
    source: str
    internals: dict[str, Any]


def generate(composition: Composition) -> Generated:
    """Emit the source for a composition, deciding the password along the way."""
    rng = random.Random(composition.seed ^ 0x5EED)
    password, params = _make_password(composition, rng)
    fmt = FORMATS[composition.format]
    if not fmt.matches(password):
        raise ValueError(
            f"password {password!r} does not satisfy format {composition.format!r}"
        )
    ctx = GenContext(composition=composition, params=params)

    layers: list[Layer] = []
    for index, name in enumerate(composition.techniques, start=1):
        emitter = _EMITTERS[name]
        layers.append(emitter(f"acm_layer_{index}", password, rng, ctx))

    helpers = _collect_helpers(layers)
    prefix = _feature_helpers(composition, rng)

    order = list(range(1, len(layers) + 1))
    rng.shuffle(order)

    dispatcher = _dispatcher(composition, layers, order, rng)
    main = _main(composition, rng)

    header = (
        "/* crackme_%03d\n"
        " * A generated practice target. Work out the accepted input, then report it:\n"
        " *   python autocrackme.py submit %d --password <what you found>\n"
        " *\n"
        " * Generated by autocrackme. Layers, keys and layout are randomised per run.\n"
        " */\n"
    ) % (composition.challenge_id, composition.challenge_id)

    source = header + main.replace(
        "__BODY__", "\n\n".join(part for part in (prefix, helpers, _join_layers(layers), dispatcher) if part)
    )
    return Generated(
        source=source,
        password=password,
        composition=composition,
        internals=[
            {"technique": name, **layer.internals}
            for name, layer in zip(composition.techniques, layers)
        ],
    )


def _make_password(composition: Composition, rng: random.Random) -> tuple[str, dict[str, Any]]:
    """Produce the answer, letting a password-source technique dictate it."""
    if "tea" in composition.techniques:
        key = [rng.getrandbits(32) for _ in range(4)]
        words = struct.unpack("<4I", TEA_MARKER)
        e0 = _xtea_encrypt(words[0], words[1], key)
        e1 = _xtea_encrypt(words[2], words[3], key)
        cipher = struct.pack("<4I", e0[0], e0[1], e1[0], e1[1])
        return cipher.hex(), {"tea_key": key}
    return FORMATS[composition.format].make(rng), {}


def _join_layers(layers: list[Layer]) -> str:
    return "\n\n".join(layer.source for layer in layers)


def _collect_helpers(layers: list[Layer]) -> str:
    """Emit each helper once, even if several layers need it."""
    seen: dict[str, str] = {}
    for layer in layers:
        for chunk in layer.helpers.split("\n\n"):
            if not chunk.strip():
                continue
            key = chunk.split("\n", 1)[0]
            seen.setdefault(key, chunk)
    return "\n\n".join(seen.values())


# -- C helpers --------------------------------------------------------------


def _c_bytes(values: list[int] | bytes, indent: str = "    ") -> str:
    data = list(values)
    rows = []
    for i in range(0, len(data), 12):
        rows.append(indent + ", ".join("0x%02X" % b for b in data[i : i + 12]))
    return ",\n".join(rows)


def _c_u32(values: list[int]) -> str:
    return ", ".join("0x%08Xu" % v for v in values)


def _rol8(value: int, amount: int) -> int:
    amount &= 7
    return ((value << amount) | (value >> ((8 - amount) & 7))) & 0xFF


def _copy_helpers() -> str:
    return """static int acm_is_digit(char c) { return c >= '0' && c <= '9'; }

static int acm_hex_val(int c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}"""


# -- Layer emitters ---------------------------------------------------------


def _plain_strcmp(fn: str, password: str, rng: random.Random, ctx: GenContext) -> Layer:
    source = (
        "ACM_NOINLINE static int %s(const char *input)\n"
        "{\n"
        '    static const char *secret = "%s";\n'
        "    return strcmp(input, secret) == 0;\n"
        "}"
    ) % (fn, password)
    return Layer("", source, {"secret": password})


def _xor_mask(fn: str, password: str, rng: random.Random, ctx: GenContext) -> Layer:
    key = rng.randrange(1, 256)
    enc = [ord(c) ^ key for c in password]
    n = len(password)
    source = (
        "ACM_NOINLINE static int %s(const char *input)\n"
        "{\n"
        "    static const unsigned char enc[%d] = {\n%s\n    };\n"
        "    const unsigned char key = 0x%02X;\n"
        "    unsigned int i;\n"
        "    if (strlen(input) != %d) return 0;\n"
        "    for (i = 0; i < %d; i++) {\n"
        "        if ((unsigned char)((unsigned char)input[i] ^ key) != enc[i]) return 0;\n"
        "    }\n"
        "    return 1;\n"
        "}"
    ) % (fn, n, _c_bytes(enc), key, n, n)
    return Layer("", source, {"key": key, "masked": enc})


def _per_char_table(fn: str, password: str, rng: random.Random, ctx: GenContext) -> Layer:
    key = rng.randrange(1, 256)
    table = [((ord(c) ^ key) + i) & 0xFF for i, c in enumerate(password)]
    n = len(password)
    source = (
        "ACM_NOINLINE static int %s(const char *input)\n"
        "{\n"
        "    static const unsigned char tab[%d] = {\n%s\n    };\n"
        "    const unsigned char key = 0x%02X;\n"
        "    unsigned int i;\n"
        "    if (strlen(input) != %d) return 0;\n"
        "    for (i = 0; i < %d; i++) {\n"
        "        unsigned char v = (unsigned char)((((unsigned char)input[i] ^ key) + i) & 0xFF);\n"
        "        if (v != tab[i]) return 0;\n"
        "    }\n"
        "    return 1;\n"
        "}"
    ) % (fn, n, _c_bytes(table), key, n, n)
    return Layer("", source, {"key": key, "table": table})


def _weighted_sum(fn: str, password: str, rng: random.Random, ctx: GenContext) -> Layer:
    digits = [int(c) for c in password]
    total = sum(d * (i % 5 + 1) for i, d in enumerate(digits))
    pair = digits[0] + digits[-1]
    n = len(digits)
    source = (
        "ACM_NOINLINE static int %s(const char *input)\n"
        "{\n"
        "    int digits[%d];\n"
        "    int count = 0;\n"
        "    long long sum = 0;\n"
        "    int i;\n"
        "    const char *p;\n"
        "    for (p = input; *p; ++p) {\n"
        "        if (!acm_is_digit(*p)) return 0;\n"
        "        if (count >= %d) return 0;\n"
        "        digits[count++] = *p - '0';\n"
        "    }\n"
        "    if (count != %d) return 0;\n"
        "    for (i = 0; i < %d; i++) sum += (long long)digits[i] * (i %% 5 + 1);\n"
        "    if (sum != %dLL) return 0;\n"
        "    if (digits[0] + digits[%d] != %d) return 0;\n"
        "    return 1;\n"
        "}"
    ) % (fn, n, n, n, n, total, n - 1, pair)
    return Layer(_copy_helpers(), source, {"weighted_sum": total, "digit_pair": pair})


def _crc32(fn: str, password: str, rng: random.Random, ctx: GenContext) -> Layer:
    target = binascii.crc32(password.encode()) & 0xFFFFFFFF
    n = len(password)
    helpers = """static uint32_t acm_crc32(const unsigned char *data, size_t len)
{
    uint32_t crc = 0xFFFFFFFFu;
    size_t i;
    int k;
    for (i = 0; i < len; i++) {
        crc ^= data[i];
        for (k = 0; k < 8; k++) {
            crc = (crc >> 1) ^ (0xEDB88320u & (uint32_t)(-(int)(crc & 1u)));
        }
    }
    return crc ^ 0xFFFFFFFFu;
}"""
    source = (
        "ACM_NOINLINE static int %s(const char *input)\n"
        "{\n"
        "    if (strlen(input) != %d) return 0;\n"
        "    return acm_crc32((const unsigned char *)input, %d) == 0x%08Xu;\n"
        "}"
    ) % (fn, n, n, target)
    return Layer(helpers, source, {"crc32": target})


def _hash_fnv(fn: str, password: str, rng: random.Random, ctx: GenContext) -> Layer:
    fnv = 0x811C9DC5
    djb = 5381
    for ch in password.encode():
        fnv = ((fnv ^ ch) * 16777619) & 0xFFFFFFFF
        djb = (djb * 33 + ch) & 0xFFFFFFFF
    n = len(password)
    helpers = """static uint32_t acm_fnv1a(const char *s)
{
    uint32_t h = 2166136261u;
    while (*s) { h ^= (unsigned char)*s++; h *= 16777619u; }
    return h;
}

static uint32_t acm_djb2(const char *s)
{
    uint32_t h = 5381u;
    while (*s) h = h * 33u + (unsigned char)*s++;
    return h;
}"""
    source = (
        "ACM_NOINLINE static int %s(const char *input)\n"
        "{\n"
        "    if (strlen(input) != %d) return 0;\n"
        "    if (acm_fnv1a(input) != 0x%08Xu) return 0;\n"
        "    return acm_djb2(input) == 0x%08Xu;\n"
        "}"
    ) % (fn, n, fnv, djb)
    return Layer(helpers, source, {"fnv1a": fnv, "djb2": djb})


def _layered(fn: str, password: str, rng: random.Random, ctx: GenContext) -> Layer:
    n = len(password)
    key1 = rng.randrange(1, 256)
    mask = [rng.randrange(256) for _ in range(n)]
    three_stages = len(ctx.composition.techniques) == 1
    perm = list(range(n))
    if three_stages:
        rng.shuffle(perm)

    stage1 = [((ord(c) ^ key1) + i) & 0xFF for i, c in enumerate(password)]
    target = [(_rol8(stage1[perm[i]], 3) ^ mask[i]) & 0xFF for i in range(n)]

    perm_decl = ""
    perm_index = "i"
    if three_stages:
        perm_decl = "    static const unsigned char perm[%d] = {\n%s\n    };\n" % (n, _c_bytes(perm))
        perm_index = "perm[i]"

    source = (
        "ACM_NOINLINE static int %s(const char *input)\n"
        "{\n"
        "    static const unsigned char target[%d] = {\n%s\n    };\n"
        "    static const unsigned char mask[%d] = {\n%s\n    };\n"
        "%s"
        "    unsigned char stage1[%d];\n"
        "    unsigned char stage2[%d];\n"
        "    const unsigned char key = 0x%02X;\n"
        "    unsigned int i;\n"
        "    if (strlen(input) != %d) return 0;\n"
        "    for (i = 0; i < %d; i++) {\n"
        "        stage1[i] = (unsigned char)((((unsigned char)input[i] ^ key) + i) & 0xFF);\n"
        "    }\n"
        "    for (i = 0; i < %d; i++) {\n"
        "        unsigned char v = stage1[%s];\n"
        "        stage2[i] = (unsigned char)(((v << 3) | (v >> 5)) ^ mask[i]);\n"
        "    }\n"
        "    return memcmp(stage2, target, %d) == 0;\n"
        "}"
    ) % (
        fn,
        n, _c_bytes(target),
        n, _c_bytes(mask),
        perm_decl,
        n, n,
        key1,
        n, n, n,
        perm_index,
        n,
    )
    return Layer(
        "",
        source,
        {"key": key1, "mask": mask, "perm": perm if three_stages else None, "stages": 3 if three_stages else 2},
    )


def _tea(fn: str, password: str, rng: random.Random, ctx: GenContext) -> Layer:
    key = [int(k) for k in ctx.params.get("tea_key") or []]
    if len(key) != 4:
        raise ValueError("tea layer requires a password-source key")
    words = struct.unpack("<4I", TEA_MARKER)
    e0 = _xtea_encrypt(words[0], words[1], key)
    e1 = _xtea_encrypt(words[2], words[3], key)
    cipher = struct.pack("<4I", e0[0], e0[1], e1[0], e1[1])
    assert cipher.hex() == password, "emitted key does not match the composition password"

    helpers = """static const uint32_t acm_tea_key[4] = { %s };

static void acm_tea_decrypt(uint32_t *v)
{
    uint32_t v0 = v[0], v1 = v[1];
    uint32_t sum = 0x9E3779B9u * 32u;
    uint32_t i;
    for (i = 0; i < 32; i++) {
        v1 -= (((v0 << 4) ^ (v0 >> 5)) + v0) ^ (sum + acm_tea_key[(sum >> 11) & 3]);
        sum -= 0x9E3779B9u;
        v0 -= (((v1 << 4) ^ (v1 >> 5)) + v1) ^ (sum + acm_tea_key[sum & 3]);
    }
    v[0] = v0;
    v[1] = v1;
}""" % _c_u32(key)

    source = (
        "ACM_NOINLINE static int %s(const char *input)\n"
        "{\n"
        "    static const unsigned char target[16] = {\n%s\n    };\n"
        "    unsigned char raw[16];\n"
        "    uint32_t block[4];\n"
        "    int i;\n"
        "    if (strlen(input) != 32) return 0;\n"
        "    for (i = 0; i < 32; i++) {\n"
        "        int v = acm_hex_val((unsigned char)input[i]);\n"
        "        if (v < 0) return 0;\n"
        "        if ((i & 1) == 0) raw[i >> 1] = (unsigned char)(v << 4);\n"
        "        else raw[i >> 1] = (unsigned char)(raw[i >> 1] | v);\n"
        "    }\n"
        "    memcpy(block, raw, sizeof(block));\n"
        "    acm_tea_decrypt(&block[0]);\n"
        "    acm_tea_decrypt(&block[2]);\n"
        "    return memcmp(block, target, sizeof(target)) == 0;\n"
        "}"
    ) % (fn, _c_bytes(TEA_MARKER))
    return Layer(_copy_helpers() + "\n\n" + helpers, source, {"key": key, "plaintext": TEA_MARKER.decode()})


def _xtea_encrypt(v0: int, v1: int, key: list[int]) -> tuple[int, int]:
    """Exact inverse of the emitted decryption, in 32-bit arithmetic."""
    sum_ = 0
    for _ in range(32):
        v0 = (v0 + ((((v1 << 4) ^ (v1 >> 5)) + v1) ^ (sum_ + key[sum_ & 3]))) & 0xFFFFFFFF
        sum_ = (sum_ + TEA_DELTA) & 0xFFFFFFFF
        v1 = (v1 + ((((v0 << 4) ^ (v0 >> 5)) + v0) ^ (sum_ + key[(sum_ >> 11) & 3]))) & 0xFFFFFFFF
    return v0, v1


def _rc4_keystream(key: bytes, length: int) -> bytes:
    s = list(range(256))
    j = 0
    for i in range(256):
        j = (j + s[i] + key[i % len(key)]) & 0xFF
        s[i], s[j] = s[j], s[i]
    out = bytearray()
    a = b = 0
    for _ in range(length):
        a = (a + 1) & 0xFF
        b = (b + s[a]) & 0xFF
        s[a], s[b] = s[b], s[a]
        out.append(s[(s[a] + s[b]) & 0xFF])
    return bytes(out)


def _rc4_serial(fn: str, password: str, rng: random.Random, ctx: GenContext) -> Layer:
    payload = password.replace("-", "")
    n = len(payload)
    key = bytes(rng.randrange(256) for _ in range(8))
    stream = _rc4_keystream(key, n)
    enc = [ord(c) ^ stream[i] for i, c in enumerate(payload)]
    assert n == 12 and len(password) == 14, "serial format changed without updating the emitter"

    helpers = """static const unsigned char acm_rc4_key[8] = {
%s
};

static void acm_rc4_init(unsigned char *s, const unsigned char *key, unsigned int klen)
{
    unsigned int i, j = 0;
    unsigned char t;
    for (i = 0; i < 256; i++) s[i] = (unsigned char)i;
    for (i = 0; i < 256; i++) {
        j = (j + s[i] + key[i %% klen]) & 0xFF;
        t = s[i]; s[i] = (unsigned char)s[j]; s[j] = t;
    }
}""" % _c_bytes(key)

    source = (
        "ACM_NOINLINE static int %s(const char *input)\n"
        "{\n"
        "    static const unsigned char enc[%d] = {\n%s\n    };\n"
        "    unsigned char s[256];\n"
        "    unsigned char code[%d];\n"
        "    unsigned char out[%d];\n"
        "    unsigned int i, a = 0, b = 0;\n"
        "    unsigned char t;\n"
        "    if (strlen(input) != 14) return 0;\n"
        "    if (input[4] != '-' || input[9] != '-') return 0;\n"
        "    for (i = 0; i < 14; i++) {\n"
        "        if (i == 4 || i == 9) continue;\n"
        "        code[i < 4 ? i : (i < 9 ? i - 1 : i - 2)] = (unsigned char)input[i];\n"
        "    }\n"
        "    acm_rc4_init(s, acm_rc4_key, 8);\n"
        "    for (i = 0; i < %d; i++) {\n"
        "        a = (a + 1) & 0xFF;\n"
        "        b = (b + s[a]) & 0xFF;\n"
        "        t = s[a]; s[a] = (unsigned char)s[b]; s[b] = t;\n"
        "        out[i] = (unsigned char)(enc[i] ^ s[(s[a] + s[b]) & 0xFF]);\n"
        "    }\n"
        "    return memcmp(out, code, %d) == 0;\n"
        "}"
    ) % (fn, n, _c_bytes(enc), n, n, n, n)
    return Layer(helpers, source, {"key": list(key), "payload": payload})


def _vm(fn: str, password: str, rng: random.Random, ctx: GenContext) -> Layer:
    n = len(password)
    key = rng.randrange(1, 256)
    add = rng.randrange(1, 256)
    rot = rng.randrange(1, 8)

    code: list[int] = []
    for i in range(n):
        expect = _rol8(((ord(password[i]) ^ key) + add) & 0xFF, rot)
        code += [0x01, i, 0x02, key, 0x03, add, 0x04, rot, 0x05, expect]
    code += [0x06]

    source = (
        "ACM_NOINLINE static int %s(const char *input)\n"
        "{\n"
        "    static const unsigned char code[%d] = {\n%s\n    };\n"
        "    unsigned int pc = 0;\n"
        "    unsigned int acc = 0;\n"
        "    if (strlen(input) != %d) return 0;\n"
        "    for (;;) {\n"
        "        unsigned int op = code[pc++];\n"
        "        if (op == 0x01) {\n"
        "            unsigned int idx = code[pc++];\n"
        "            acc = (unsigned char)input[idx];\n"
        "        } else if (op == 0x02) {\n"
        "            acc = (unsigned char)(acc ^ code[pc++]);\n"
        "        } else if (op == 0x03) {\n"
        "            acc = (unsigned char)(acc + code[pc++]);\n"
        "        } else if (op == 0x04) {\n"
        "            unsigned int r = code[pc++] & 7u;\n"
        "            acc = (unsigned char)((acc << r) | (acc >> ((8u - r) & 7u)));\n"
        "        } else if (op == 0x05) {\n"
        "            if (acc != code[pc++]) return 0;\n"
        "        } else if (op == 0x06) {\n"
        "            return 1;\n"
        "        } else {\n"
        "            return 0;\n"
        "        }\n"
        "    }\n"
        "}"
    ) % (fn, len(code), _c_bytes(code), n)
    return Layer("", source, {"opcodes": code, "xor": key, "add": add, "rot": rot})


_EMITTERS = {
    "plain_strcmp": _plain_strcmp,
    "xor_mask": _xor_mask,
    "per_char_table": _per_char_table,
    "weighted_sum": _weighted_sum,
    "crc32": _crc32,
    "hash_fnv": _hash_fnv,
    "layered": _layered,
    "tea": _tea,
    "rc4_serial": _rc4_serial,
    "vm": _vm,
}


# -- Features and dispatcher ------------------------------------------------


def _feature_helpers(comp: Composition, rng: random.Random) -> str:
    chunks: list[str] = []
    if comp.features.opaque_predicates:
        chunks.append(
            "static int acm_trust(unsigned int seed)\n"
            "{\n"
            "    volatile unsigned int k = seed;\n"
            "    return ((k * (k + 1u)) & 1u) == 0;\n"
            "}"
        )
    if comp.features.decoy_function:
        table = [rng.randrange(32, 127) for _ in range(16)]
        chunks.append(
            "static int acm_validate_key(const char *input)\n"
            "{\n"
            "    static const unsigned char tab[16] = {\n%s\n    };\n"
            "    unsigned int i;\n"
            "    for (i = 0; i < 16; i++) {\n"
            "        if ((unsigned char)input[i] != tab[i]) return 0;\n"
            "    }\n"
            "    return 1;\n"
            "}" % _c_bytes(table)
        )
    if comp.features.encrypt_strings:
        key = [rng.randrange(1, 256) for _ in range(8)]
        chunks.append(
            "static const unsigned char acm_msg_key[8] = {\n%s\n};\n"
            "\n"
            "static void acm_unmask(char *dst, const unsigned char *src, unsigned int n)\n"
            "{\n"
            "    unsigned int i;\n"
            "    for (i = 0; i < n; i++) dst[i] = (char)(src[i] ^ acm_msg_key[i & 7]);\n"
            "}" % _c_bytes(key)
        )
    return "\n\n".join(chunks)


def _dispatcher(
    comp: Composition, layers: list[Layer], order: list[int], rng: random.Random
) -> str:
    lines: list[str] = []
    if comp.features.opaque_predicates:
        lines.append("    if (!acm_trust(0x%08Xu)) return 0;" % rng.getrandbits(32))
    if comp.features.antidebug:
        lines.append(
            "#if defined(_WIN32)\n"
            "    if (IsDebuggerPresent()) return 0;\n"
            "#endif"
        )
    if comp.features.decoy_function:
        lines.append(
            "    {\n"
            "        int (*volatile acm_sink)(const char *) = acm_validate_key;\n"
            "        (void)acm_sink;\n"
            "    }"
        )
    for index in order:
        lines.append("    if (!acm_layer_%d(input)) return 0;" % index)

    if comp.features.junk:
        ops = []
        for _ in range(comp.features.junk):
            choice = rng.randint(0, 3)
            if choice == 0:
                ops.append("        junk = junk * 1664525u + 1013904223u;")
            elif choice == 1:
                ops.append("        junk ^= (junk << 7) | (junk >> 25);")
            elif choice == 2:
                ops.append("        junk += 0x%08Xu;" % rng.getrandbits(32))
            else:
                ops.append("        junk -= 0x%08Xu;" % rng.getrandbits(32))
        ops.append("        if (junk == 0x00000000u && junk != 0x00000000u) return 0;")
        lines.append(
            "    {\n"
            "        volatile unsigned int junk = 0x%08Xu;\n"
            "%s\n"
            "    }" % (rng.getrandbits(32), "\n".join(ops))
        )
    lines.append("    return 1;")

    body = "\n".join(lines)
    return (
        "static int check(const char *input)\n"
        "{\n"
        "%s\n"
        "}"
    ) % body


# -- main -------------------------------------------------------------------

_PROMPTS = {"digits": "Enter the serial: ", "serial": "Enter the serial: ", "hex32": "Enter the token: "}
DEFAULT_PROMPT = "Enter the password: "
OK_TEXT = "Correct! That is the answer."
BAD_TEXT = "Wrong."

_PLAIN_MAIN = """#include <stdio.h>
#include <string.h>
#include <stdint.h>
#if defined(_WIN32)
#include <windows.h>
#endif

#define ACM_NOINLINE __declspec(noinline)

__BODY__

int main(void)
{
    char input[256];
    size_t len;

    fputs("__PROMPT__", stdout);
    fflush(stdout);
    if (fgets(input, (int)sizeof(input), stdin) == NULL) return 1;

    len = strlen(input);
    while (len > 0 && (input[len - 1] == '\\n' || input[len - 1] == '\\r')) {
        input[--len] = '\\0';
    }

    if (check(input)) {
        puts("__OK__");
        return 0;
    }
    puts("__BAD__");
    return 1;
}
"""

_MASKED_MAIN = """#include <stdio.h>
#include <string.h>
#include <stdint.h>
#if defined(_WIN32)
#include <windows.h>
#endif

#define ACM_NOINLINE __declspec(noinline)

__BODY__

static const unsigned char acm_msg_prompt[] = { __PROMPT__ };
static const unsigned char acm_msg_ok[] = { __OK__ };
static const unsigned char acm_msg_bad[] = { __BAD__ };

int main(void)
{
    char input[256];
    char prompt[64], ok[32], bad[32];
    size_t len;

    acm_unmask(prompt, acm_msg_prompt, (unsigned int)sizeof(acm_msg_prompt));
    acm_unmask(ok, acm_msg_ok, (unsigned int)sizeof(acm_msg_ok));
    acm_unmask(bad, acm_msg_bad, (unsigned int)sizeof(acm_msg_bad));

    fputs(prompt, stdout);
    fflush(stdout);
    if (fgets(input, (int)sizeof(input), stdin) == NULL) return 1;

    len = strlen(input);
    while (len > 0 && (input[len - 1] == '\\n' || input[len - 1] == '\\r')) {
        input[--len] = '\\0';
    }

    if (check(input)) {
        puts(ok);
        return 0;
    }
    puts(bad);
    return 1;
}
"""


def _mask(text: str, key: list[int]) -> list[int]:
    return [(ord(ch) ^ key[i & 7]) for i, ch in enumerate(text)] + [key[len(text) & 7]]


def _main(comp: Composition, rng: random.Random) -> str:
    prompt = _PROMPTS.get(comp.format, DEFAULT_PROMPT)
    if not comp.features.encrypt_strings:
        return (
            _PLAIN_MAIN.replace("__PROMPT__", prompt)
            .replace("__OK__", OK_TEXT)
            .replace("__BAD__", BAD_TEXT)
        )

    key = [rng.randrange(1, 256) for _ in range(8)]
    template = _MASKED_MAIN
    template = template.replace("__PROMPT__", _c_bytes(_mask(prompt, key), indent=""))
    template = template.replace("__OK__", _c_bytes(_mask(OK_TEXT, key), indent=""))
    template = template.replace("__BAD__", _c_bytes(_mask(BAD_TEXT, key), indent=""))
    return template


def technique_titles(comp: Composition) -> list[str]:
    return [POOL[name].title for name in comp.techniques]
